### ISSUE TITLE
Module 2: Word Cloud

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-tool#74]
## Research Results
[Javascript Word-Cloud implementation based on wordcloud2.js](https://github.com/timdream/wordcloud2.js)

## Description
- Each user-details timeline gets a word cloud of the most used words in their last 200 tweets/retweets
- Word Cloud changes not with timeline sort changes (unnecessary feature for now)

## Feature Checklist
- [x] #75 add cloud javascript
- [x] #77 generate word cloud
- [x] #85 add cloud options to user settings (checkboxes for displaying hashtags, handles, words)
- [x] #86 click words in cloud to display corresponding tweets underneath, reset by clicking an empty area in the cloud canvas

## Further Improvements
- Click on word to see just matching timeline tags
    - other words are grayed out and little x to reset appears in the top where the hint button normaly is or next to it

**Comment by jonathanschlue** [comment]
@Eik-S Seems to be done, right?

**Comment by jonathanschlue** [comment]
@Eik-S: I think #102 and #103 both belong to this epic, too, right?
