### ISSUE TITLE
Module 1: Beta Version

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-tool#8]
## Complete Beta Version containing the following:
- [x] **Graph Logic**
  - [x] Retrieve Twitter retweet data
  - [x] Retrieve Database user relation data
  - [x] Crosscheck both to define the tracemap relations
- [x] **Graph Visualization**
  - [x] Highlighting of neighbors on hover
  - [x] Adjust forces for highest readability
- [x] **User Information**
  - [x] Define user Information html template
  - [x] Retrieve user data from twitter/database
  - [x] Show information when clicking the users node
  - [x] Add timeline of tweets, sortable by relevance or date
  - [x] Generate new tracemap with a click on a tweet
- [x] **Add share buttons for tracemap**
  - [x] Twitter
  - [x] Facebook
  - [x] Mail
- [x] **Add the header**
  - [x] Small search bar
  - [x] Link to the landing page
  - [x] Link to a full description
  - [x] Link to our ethical standarts
- [x] Implement new design
  - [x] Graph
    - [x] Settings
    - [x] Zooming
  - [x] Sidepanel
    - [x] Searchbar
    - [x] Share Button
    - [x] Accordeons
      - [x] Source
      - [x] Influential Users
      - [x] Metrics
      - [x] Enhanced Metrics
      - [x] Last TraceMaps
  - [x] Userpanel
